sculpin_content_types:
  geeks:
    type: path
    path: _geeks
    singular_name: geek
    enabled: true

  posts:
    permalink: blog/:year/:month/:day/:filename/

sculpin_pagination:
  max_per_page: 10

sculpin_theme:
    theme: tekkie/tekkie
